#!/bin/bash

# enter configuration values
MONGO_DATABASE="your_db_name"
APP_NAME="your_app_name"
MONGO_HOST="127.0.0.1"
MONGO_PORT="27017"
BACKUPS_DIR="/home/username/backups/$APP_NAME"
APP_DIR="/var/www/appname"
S3_BUCKET="your_bucket"

DB_BACKUP_NAME="$MONGO_DATABASE-$TIMESTAMP"
APP_BACKUP_NAME="$APP_NAME-$TIMESTAMP"
TIMESTAMP=`date +%F-%H%M`

function print_task
{
  printf "\n==> ${1}\n\n"
}

function print_header
{
  echo "-------------------------------------------------------------------------------"
  printf "\n  ${1}\n\n"
  echo "-------------------------------------------------------------------------------"
}

print_header "Backing up database ($APP_NAME)"
print_task "Backup destination ($BACKUPS_DIR)"

# mongo admin --eval "printjson(db.fsyncLock())"
# $MONGODUMP_PATH -h $MONGO_HOST:$MONGO_PORT -d $MONGO_DATABASE
mongodump -d $MONGO_DATABASE -o $BACKUPS_DIR
# mongo admin --eval "printjson(db.fsyncUnlock())"

# compress database files
tar -zcvf $BACKUPS_DIR/$DB_BACKUP_NAME.tgz $BACKUPS_DIR/$MONGO_DATABASE

print_task "Backup destination ($BACKUPS_DIR)"
rm -rf $BACKUPS_DIR/$MONGO_DATABASE

# compress the application files
# filtered files
NODE_MODULES="node_modules"
FW_NODE_MODULES="$APP_DIR/adapt_framework/node_modules"
GIT_FILES="$APP_DIR/.git"

# TODO excludes are not currently working, could be white space sensitivity
#tar -zcvf --exclude=$NODE_MODULES --exclude=$FW_NODE_MODULES --exclude=$GIT_FILES $BACKUPS_DIR/$APP_BACKUP_NAME.tgz $APP_DIR

tar -zcvf $BACKUPS_DIR/$APP_BACKUP_NAME.tgz $APP_DIR

# Copy application and database to Amazon S3
# needs check for files existen
aws s3 cp $BACKUPS_DIR/$DB_BACKUP_NAME.tgz s3://$S3_BUCKET/

aws s3 cp $BACKUPS_DIR/$APP_BACKUP_NAME.tgz s3://$S3_BUCKET/

# remove local files
rm $BACKUPS_DIR/$APP_BACKUP_NAME.tgz
rm $BACKUPS_DIR/$DB_BACKUP_NAME.tgz

print_task "Backup finished ($TIMESTAMP)"
