#!/bin/bash

MONGO_DATABASE="your_db_name"
APP_NAME="your_app_name"
APP_DIR="your_app_path"

MONGO_HOST="127.0.0.1"
MONGO_PORT="27017"
TIMESTAMP=`date +%F-%H%M`
BACKUPS_DIR="/home/username/backups/$APP_NAME"
BACKUP_NAME="$APP_NAME-$TIMESTAMP"



function print_task
{
  printf "\n==> ${1}\n\n"
}

function print_header
{
  echo "-------------------------------------------------------------------------------"
  printf "\n  ${1}\n\n"
  echo "-------------------------------------------------------------------------------"
}

print_header "Backing up database ($APP_NAME)"
print_task "Backup destination ($BACKUPS_DIR)"

# mongo admin --eval "printjson(db.fsyncLock())"
# $MONGODUMP_PATH -h $MONGO_HOST:$MONGO_PORT -d $MONGO_DATABASE
mongodump -d $MONGO_DATABASE -o $BACKUPS_DIR
# mongo admin --eval "printjson(db.fsyncUnlock())"


tar -zcvf $BACKUPS_DIR/$BACKUP_NAME.tgz $BACKUPS_DIR/$MONGO_DATABASE

print_task "Backup destination ($BACKUPS_DIR)"
rm -rf $BACKUPS_DIR/$MONGO_DATABASE

# backup the application

print_task "Backup finished ($TIMESTAMP)"
